# Generated by Django 4.1.5 on 2023-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_myuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="userid",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
