# Generated by Django 4.1.5 on 2023-04-06 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_myuser_userid_alter_myuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
