# Generated by Django 4.1.5 on 2023-04-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_myuser_date_joined"),
    ]

    operations = [
        migrations.DeleteModel(name="UserAPIKey",),
    ]
