# Generated by Django 4.1.5 on 2023-04-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_delete_userapikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True, null=True)),
                ("temp", models.IntegerField(blank=True, null=True)),
                ("humidity", models.IntegerField(blank=True, null=True)),
                ("rainType", models.IntegerField(blank=True, null=True)),
                ("rainfall", models.CharField(blank=True, max_length=20, null=True)),
                ("sky", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
