# Generated by Django 4.1.5 on 2023-04-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_weatherdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("opening_hours", models.CharField(max_length=50)),
                ("main_item", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
    ]
