# Generated by Django 4.1.6 on 2023-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_culturebank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturebank',
            name='description',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='main_item',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='name',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='culturebank',
            name='explanation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='item',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='marketHours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='marketImg',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='marketName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='reivew',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='sectionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturebank',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='culturebank',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
