# Generated by Django 4.1.6 on 2023-04-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_culturebank_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturebank',
            name='item',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='marketHours',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='marketImg',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='marketName',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='culturebank',
            name='sectionNumber',
        ),
        migrations.AddField(
            model_name='culturebank',
            name='main_item',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='market_hours',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='name',
            field=models.CharField(default='some_value', max_length=50),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='culturebank',
            name='section_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='culturebank',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='culturebank',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='culturebank',
            name='explanation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='culturebank',
            name='grade',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='culturebank',
            name='idx',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='culturebank',
            name='reivew',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
