# Generated by Django 4.1.6 on 2023-04-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_culturebank_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturebank',
            name='market_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
