# Generated by Django 4.1.5 on 2023-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_culturebank_market_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="fineDustDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True, null=True)),
                ("dataTime", models.CharField(blank=True, max_length=20, null=True)),
                ("pm10", models.IntegerField(blank=True, null=True)),
                ("pm10Grade", models.CharField(blank=True, max_length=20, null=True)),
                ("pm2_5", models.IntegerField(blank=True, null=True)),
                ("pm2_5Grade", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
