# Generated by Django 4.1.5 on 2023-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_finedustdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_login_id", models.CharField(max_length=1000, null=True)),
                ("email", models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
