# Generated by Django 4.1.7 on 2023-05-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yeouijus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeouijus', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
